services:
  products.database:
     image: postgres 
     restart: always
     container_name: products.database
     environment:
        - POSTGRES_DB=CarDb
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
     volumes:
        - ./.containers/products-db:/var/lib/postgresql/data 
     ports:
        - "5432:5432" 
      
  test_car.api:
    image: testcarapi
    build:
      context: .
      dockerfile: Test_Car/Dockerfile
    environment:
         ASPNETCORE_ENVIRONMENT: Development
    ports:
        - "8080:8080" 
        - "8081:8081"
    depends_on:
       - products.database
volumes:
  postgres_data: {}
